services:
  - type: web
    name: tinkhec-demo
    env: java
    region: oregon
    buildCommand: cd main && ./mvnw clean install -DskipTests
    startCommand: cd main && java -Dspring.profiles.active=prod -Dserver.port=$PORT -jar target/main-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_OPTS
        value: -Xmx512m -Xms256m


