services:
  - type: web
    name: tinkhec-demo
    runtime: java
    buildCommand: cd main && mvn clean install -DskipTests
    startCommand: cd main && java -jar target/main-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_OPTS
        value: -Xmx512m -Xms256m
      - key: SERVER_PORT
        value: 8080
    healthCheckPath: /login
    autoDeploy: true
